### ISSUE TITLE
"Error: GraphQL request failed." after calling pnpm build:eas --profile local

### ISSUE THREAD

**Issue by nicolasdev1** [outsung/expo-repack#1]
Hi, @outsung! I've been looking for a working Expo + Repack template for a while and I finally found yours, thank you very much for your contribution!

I followed the step-by-step instructions indicated, but when trying to call `pnpm build:eas --profile local` I am having the following error:

![image](https://github.com/outsung/expo-repack-monorepo/assets/56241288/beeff872-0312-4ea7-b278-9b2d4818395a)

Have you ever faced something similar? I'm trying to resolve it but without success. My env details:

**Node**
`v20.10.0`

**PNPM**
`8.12.1`

**EAS-CLI**
`eas-cli/7.2.0 darwin-arm64 node-v20.10.0`

**Comment by outsung** [comment]
Thank you for your interest in this repo!! @nicolasdev1 

Well, I've never seen an error like this before

I think it's a network problem, but I don't know
https://github.com/expo/eas-cli/issues/2081

This step is just an eas build, so I don't think it's a problem with my code, so I'll close the issue
